[package]
name = "rust-ray-tracing"
version = "1.0.0"
edition = "2021"
authors = ["TwentyFive <twentyfivesoftware@gmail.com>"]
repository = "https://github.com/TwentyFiveSoftware/rust-ray-tracing"

[dependencies]
image = "0.24.2"
rand = "0.8.5"
